const fs = require('fs');
const { OpenAI } = require('openai');

exports.summarizeMeeting = async (req, res) => {
    try {
        if (!process.env.OPENAI_API_KEY) {
            return res.status(500).json({ success: false, message: "Server configuration error: OpenAI API Key is missing." });
        }

        // Initialize OpenAI configuring it with the API key from the .env file.
        const openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY,
        });

        // req.file should contain the uploaded audio file generated by multer
        if (!req.file) {
            return res.status(400).json({ success: false, message: "No audio file provided" });
        }

        const audioFilePath = req.file.path;

        // 1. Transcription (Speech-to-Text) using OpenAI Whisper API
        const transcription = await openai.audio.transcriptions.create({
            file: fs.createReadStream(audioFilePath),
            model: "whisper-1",
            response_format: "text", // optional: specifies the returned format
        });

        const transcriptText = transcription.text || transcription;

        if (!transcriptText || transcriptText.trim() === "") {
            fs.unlinkSync(audioFilePath);
            return res.status(400).json({ success: false, message: "Could not extract audio or audio is empty." });
        }

        // 2. Summarization using OpenAI Chat completions API
        // Configure the prompt to extract key points and summarize the meeting
        const completion = await openai.chat.completions.create({
            model: "gpt-3.5-turbo",
            messages: [
                { role: "system", content: "You are a professional meeting assistant. Please create a concise summary of the provided meeting transcript, highlighting key decisions, main discussion points, and any action items." },
                { role: "user", content: `Here is the meeting transcript:\n\n${transcriptText}` }
            ],
            temperature: 0.7,
        });

        const summaryText = completion.choices[0].message.content;

        // Clean up the uploaded file from the server
        fs.unlinkSync(audioFilePath);

        return res.status(200).json({
            success: true,
            message: "Meeting summarized successfully",
            data: {
                transcript: transcriptText,
                summary: summaryText
            }
        });

    } catch (error) {
        console.error("Error summarizeMeeting:", error);

        // Clean up on error
        if (req.file && req.file.path && fs.existsSync(req.file.path)) {
            fs.unlinkSync(req.file.path);
        }

        return res.status(500).json({
            success: false,
            message: "Failed to summarize meeting",
            error: error.message
        });
    }
};
